USE ujian_online;

SET @db := DATABASE();

SET @sql := IF(
  NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='exams' AND COLUMN_NAME='access_code'),
  'ALTER TABLE exams ADD COLUMN access_code VARCHAR(32) NULL UNIQUE',
  'SELECT 1'
); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

SET @sql := IF(
  NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='exams' AND COLUMN_NAME='randomize_questions'),
  'ALTER TABLE exams ADD COLUMN randomize_questions TINYINT(1) NOT NULL DEFAULT 0',
  'SELECT 1'
); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

SET @sql := IF(
  NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='exams' AND COLUMN_NAME='randomize_options'),
  'ALTER TABLE exams ADD COLUMN randomize_options TINYINT(1) NOT NULL DEFAULT 0',
  'SELECT 1'
); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

CREATE TABLE IF NOT EXISTS attempt_questions (
  attempt_id BIGINT UNSIGNED NOT NULL,
  question_id BIGINT UNSIGNED NOT NULL,
  display_order INT NOT NULL,
  option_map JSON NULL,
  PRIMARY KEY(attempt_id,question_id),
  UNIQUE KEY attempt_display_order (attempt_id,display_order),
  FOREIGN KEY(attempt_id) REFERENCES attempts(id) ON DELETE CASCADE,
  FOREIGN KEY(question_id) REFERENCES questions(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS exam_participants (
  exam_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(exam_id,user_id),
  FOREIGN KEY(exam_id) REFERENCES exams(id) ON DELETE CASCADE,
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NULL,
  exam_id BIGINT UNSIGNED NULL,
  attempt_id BIGINT UNSIGNED NULL,
  event_type VARCHAR(80) NOT NULL,
  event_data JSON NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX(created_at), INDEX(event_type)
) ENGINE=InnoDB;

SET @db := DATABASE();
SET @sql := IF(
  NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='questions' AND COLUMN_NAME='question_image'),
  'ALTER TABLE questions ADD COLUMN question_image VARCHAR(500) NULL AFTER question_text',
  'SELECT 1'
); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
